version: '2'
services:

  # Define a PHP webserver
  php-webserver:
    # Use a PHP image with apache
    #image: fpfis/php56-dev
    image: myapp
    #working_dir: /app
    # Define settings
    environment:
      - XDEBUG=true
      - DOCUMENT_ROOT=/app
    # Mount a local volume in the container
    volumes:
      - ./:/app/build
    # Share the container port with the host
    ports:
      - 8080:8080 

  # Define a mysql service
  mysql:
    image: fpfis/mysql56


